### PR TITLE
Add getRunningGameInfo2

### PR DESCRIPTION
**Pull request by antonk777**
add getRunningGameInfo2

### CODE REVIEW

**Review by EladBahar — COMMENTED** [review]
that's not accureate :
interface GetRunningGameInfoResult  {
    isInFocus: boolean;
    isRunning: boolean;
    allowsVideoCapture: boolean;
    title: string;
    displayName: string;
    shortTitle: string;
    id: number;
    classId: number;
    width: number;
    height: number;
    logicalWidth: number;
    logicalHeight: number;
    renderers: string[];
    detectedRenderer: string;
    executionPath: string;
    sessionId: string;
    commandLine: string;
    type: GameInfoType;
    typeAsString: string;
    windowHandle: { value: number; };
    monitorHandle: { value: number; };
    processId: number;
    overlayInfo: OverlayInfo;
  }   

interface GetRunningGameInfoResult2 : extand Result {
gameInfo: GetRunningGameInfoResult  
}

**Comment by eransharv** [comment]
@antonk777 FYI

**Comment by antonk777** [comment]
@EladBahar what's inaccurate?

**Comment by eransharv** [comment]
@EladBahar, can you please push a corrected fix?

**Comment by EladBahar** [comment]
i wrote it in the comment

**Comment by eransharv** [comment]
@EladBahar I merged the fix FYI

**Pull request merged**
